### ISSUE TITLE
Public key derivation?

### ISSUE THREAD

**Issue by bmclain** [coranos/coranos.github.io#14]
Thanks for making this tool, it's helpful for some testing I'm doing with address generation.

Do you know of any way to extract a public key at the account level, and then derive child addresses via the public key only? I've tried the following:

```
const seed = bip39.mnemonicToSeed('some garbage mnemonic');
const node = bip32.fromSeed(seed);
const bip44path = 'm/44\'/888\'/0\'';
const pathNode = node.derivePath(bip44path);
const pubkey = pathNode.neutered().toBase58();
const hdnode = bitcoinjs.HDNode.fromBase58(pubkey);
const childNode = hdnode.derive(0).derive(7);
console.log(childNode.getAddress());
```

The address I get starts with a 1, not an A and doesn't seem to be a valid NEO address. As soon as I remove the `neutered()` part the address generates correctly. If you have any ideas on how to deterministically generate the same addresses via a private key and a public key with NEO, I would be eternally grateful.

**Comment by coranos** [comment]
I don't really have an answer for you, since I just took the other guy's code and changed it to work with neo.

I can say three things though: 
1: neutering is discussed in the bip32 paper i linked below
2: I think the address you are logging is what neo calls a 'scripthash'. You'd need to use the neo specific code that adds the A at the beginning.
3: You can always use a public key as a private key and derive a secondary public key, but that usually means your private key is on the blockchain (as a public key).

https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki

**Comment by bmclain** [comment]
@coranos I've been playing around with neon-js to try to reverse engineer the address stuff and haven't really had any luck. I'm getting the feeling that there just isn't a straightforward way to derivate addresses via a public key?  NEO seems to completely eschew bip32.

**Comment by coranos** [comment]
The only hard part is scripthash to private key. Have you looked int my blue-app-neo or neo-java code? They probably have cleaner code than neon-js
